version: '3.4'

services:
  db:
    image: sepulveda/mysql:v1
    ports:
      - 33069:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

  vuejs:
    image: sepulveda/node:v1
    ports: 
      - 8080:8080

  cakephp:
    image: sepulveda/back_cakephp:v1
    ports:
      - 8100:80
    depends_on:
      - db